### ISSUE TITLE
cannot publish chinese post?

### ISSUE THREAD

**Issue by luckypoem** [amyreese/nib#1]
hi.
i write a chinese post:
as3:~/nib/sample# cat ~/nib/sample/documents/posts/test3.md
title: test3
description: xx
date: 2013-11-24
tags: misc
## author: ym

这是测试3.
as3:~/nib/sample#
but i cannot publish the chinese post successfully:

as3:~/nib/sample# nib -c config.nib build
Reading documents/about.md
Reading documents/posts/test1.md
Reading documents/posts/test3.md
Reading documents/posts/first.md
Reading documents/posts/test2.md
Reading documents/posts/fengyuwuzu.md
Reading documents/links/nib.md
Reading resources/main.less
Reading resources/favicon.ico
Reading resources/robots.txt
Running pre-processor <class 'nib.plugins.blog.BlogDateProcessor'>
Running pre-processor <class 'nib.plugins.pages.PagesProcessor'>
Running document processor <class 'nib.plugins.blog.BlogDocumentProcessor'>
Running resource processor <class 'nib.plugins.lesscss.LessCSSProcessor'>
Running markup processor <class 'nib.plugins.markdown.MarkdownProcessor'>
Error: 'ascii' codec can't decode byte 0xe8 in position 1: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
as3:~/nib/sample#

so how to publish a chinese post successfully?
i don't have this issue when using other python-based static site generators such as pelican

**Comment by amyreese** [comment]
Are you using python 2 or 3?

**Comment by luckypoem** [comment]
hi.
i'm using python2.7

**Comment by amyreese** [comment]
Unfortunately, atm, there are unicode issues when using Nib with Python
2.7, due to differences in the way UTF-8 is handled (or not handled).
Unicode support should be working if you can use Nib with Python 3.2 or
higher.  But I will try to work on fixing the UTF-8 support in Python 2.7,
though I can't say it will be fixed any time soon.

John Reese
noswap.com
