### ISSUE TITLE
nib.noswap.com demo site is security blocked to death

### ISSUE THREAD

**Issue by ssteinerx** [amyreese/nib#2]
Chrome says (September 21, 2016):

nib.noswap.com normally uses encryption to protect your information. When Google Chrome tried to connect to nib.noswap.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be nib.noswap.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit nib.noswap.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by amyreese** [comment]
Looks like I failed to include that when I switched SSL certs.  Thank you!
