### ISSUE TITLE
after i installed lessc,why still there is lessc error?

### ISSUE THREAD

**Issue by luckypoem** [amyreese/nib#3]
hi.

root@AR:~/nib/sample# pip3.5 install lessc
Collecting lessc
  Downloading lessc-0.1.2.tar.gz
Collecting asset>=0.6.10 (from lessc)
  Downloading asset-0.6.11.tar.gz
Collecting six>=1.6.0 (from lessc)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting globre>=0.0.5 (from asset>=0.6.10->lessc)
  Downloading globre-0.1.4.tar.gz
Collecting aadict>=0.2.2 (from asset>=0.6.10->lessc)
  Downloading aadict-0.2.2.tar.gz
Installing collected packages: globre, six, aadict, asset, lessc
  Running setup.py install for globre ... done
  Running setup.py install for aadict ... done
  Running setup.py install for asset ... done
  Running setup.py install for lessc ... done
Successfully installed aadict-0.2.2 asset-0.6.11 globre-0.1.4 lessc-0.1.2 six-1.10.0
root@AR:~/nib/sample# nib -c config.nib build
Reading documents/about.md
Reading documents/posts/first.md
Reading documents/links/nib.md
Reading resources/favicon.ico
Reading resources/main.less
Reading resources/robots.txt
Running pre-processor <class 'nib.plugins.blog.BlogDateProcessor'>
Running pre-processor <class 'nib.plugins.pages.PagesProcessor'>
Running document processor <class 'nib.plugins.blog.BlogDocumentProcessor'>
Running resource processor <class 'nib.plugins.lesscss.LessCSSProcessor'>
Error: lessc
root@AR:~/nib/sample#

**Comment by ssteinerx** [comment]
lessc must be installed globally as if it is only installed locally, you need to specify the specific bin path e.g. node_modules/.bin/lessc and the call in the nib code is not made that way.

```
npm install -g less
```

solves the problem.

**Comment by luckypoem** [comment]
@ssteinerx ,it does.tks

**Comment by ssteinerx** [comment]
Question answered and note made in README file in PR #4.  Please close.
